# Generated by Django 4.1.7 on 2023-08-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_data_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storestatus',
            name='downtime_last_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='storestatus',
            name='downtime_last_hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='storestatus',
            name='downtime_last_week',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='storestatus',
            name='uptime_last_day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='storestatus',
            name='uptime_last_hour',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='storestatus',
            name='uptime_last_week',
            field=models.IntegerField(null=True),
        ),
    ]
